[package]
name = "websock"
version = "0.1.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]

hyper = "0.12.25"
tokio = "0.1.18"
futures = "0.1.25"
log = "0.4"
tungstenite = "0.6"
quick-error = "1.2"
headers = "0.2"

[dev-dependencies]
pretty_env_logger = "0.3"